version: "3"
services:
  schedulit:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
